#!/bin/sh
#
# sshd        Starts sshd.
#

# Make sure the ssh-keygen progam exists
[ -f /usr/bin/ssh-keygen ] || exit 0

. /etc/init.d/functions.sh

check_ssh_key() {                                                      
    local name=$1                                                           
    local type=$2 
    
	if [ ! -f /etc/$name ] ; then
		mount_bootblock
		if [ -f /etc/bootblock/$name ]; then
			echo "recovering host $type key from bootblock... "
		else
			echo Generating $type key...
			/usr/bin/ssh-keygen -t $type -f /etc/bootblock/$name -C '' -N ''
	    fi
		cp /etc/bootblock/$name /etc/$name
	fi
}

#umount_bootblock
                
#umask 077

start() {
	# Check for the SSH1 RSA key
	#check_ssh_key ssh_host_rsa_key rsa1
                
	# Check for the SSH2 DSA key
	#check_ssh_key ssh_host_dsa_key dsa

	# Check for the SSH2 ecdsa key
	#check_ssh_key ssh_host_ecdsa_key ecdsa

 	echo -n "Starting sshd: "
	/usr/sbin/sshd
	touch /var/lock/sshd
	echo "OK"
}	
stop() {
	echo -n "Stopping sshd: "
    killall	sshd 
	rm -f /var/lock/sshd
	echo "OK" 
}
restart() {
	stop
	start
}	

case "$1" in
    start)
  	    start
	    ;;
    stop)
  	    stop
	    ;;
    restart|reload)
  	    restart
	    ;;
    *)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac

exit $?

